<a href="https://colab.research.google.com/github/Sanjayme049/Python/blob/main/asarray_fromiter_frombuffer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [3]:
a=np.array([10,20,30,40,50])


In [4]:
print(a)

[10 20 30 40 50]


In [5]:
res=np.asarray(a,dtype="float",order="C")

In [6]:
print(res)

[10. 20. 30. 40. 50.]


In [7]:
b=np.array([[10,20,30],[40,50,60]])

In [8]:
res1=np.asarray(b,dtype="int",order="F")

In [9]:
res1

array([[10, 20, 30],
       [40, 50, 60]])

In [10]:
for i in np.nditer(res1):
  print(i)

10
40
20
50
30
60


In [11]:
res2=np.asarray(b,dtype="int",order="C")

In [12]:
for i in np.nditer(res2):
  print(i)


10
20
30
40
50
60


In [13]:
s=b"hello welcome python"

In [14]:
c=np.frombuffer(s,dtype="S1",count=-1,offset=0)

In [15]:
print(c)

[b'h' b'e' b'l' b'l' b'o' b' ' b'w' b'e' b'l' b'c' b'o' b'm' b'e' b' '
 b'p' b'y' b't' b'h' b'o' b'n']


In [16]:
d=np.frombuffer(s,dtype="S1",count=10,offset=0)

In [17]:
d

array([b'h', b'e', b'l', b'l', b'o', b' ', b'w', b'e', b'l', b'c'],
      dtype='|S1')

In [18]:
e=np.frombuffer(s,dtype="S1",count=10,offset=2)
#S1 is 1 byte data

In [19]:
e

array([b'l', b'l', b'o', b' ', b'w', b'e', b'l', b'c', b'o', b'm'],
      dtype='|S1')

In [20]:
list=[10,20,30,40,50]

In [21]:
f=np.fromiter(list,dtype="float",count=-1)

In [23]:
f

array([10., 20., 30., 40., 50.])