<a href="https://colab.research.google.com/github/Sanjayme049/Python/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Numpy is a general purpose array-processing package. It provides a high performance multidimensional arry object, and tools for working with these arrays. It is the fundamental package for scientific computing with python.


import numpy as np

my_list = [1,2,3,4,5]


In [2]:
arr = np.array(my_list)

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.shape

(5,)

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
arr

array([1, 2, 3, 4, 5])

In [7]:
##Multinested array
my_lst1 = [1,2,3,4,5]
my_lst2 = [2,3,4,5,6]
my_lst3 = [9,7,6,8,9]

arr = np.array([my_lst1,my_lst2,my_lst3])

In [8]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [9]:
arr.shape


(3, 5)

In [ ]:
# arr[0:2,0:2]
# arr[:,:3]
# arr[1:,3:]
# arr[1:,:3]
# arr[1:,1:3]
# arr[2:,2:]
arr[1:2,1:4]





array([[3, 4, 5]])

In [10]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [ ]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [ ]:
#arr.reshape(1,15)

In [11]:
#Indexing in numpy

#Accessing the array element

arr=np.array([1,2,3,4,5,6,7,8,9])


In [12]:
arr[3]

4

In [ ]:
# arr[5]

In [13]:
 arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr = np.arange(0, 10, step=2)
print(arr)

[0 2 4 6 8]


In [16]:
arr = np.linspace(0, 10, 50)
arr


array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [18]:
#COPY OR BOARDCASTING FUNCTION
arr = np.arange(0, 10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr[3:]=100
arr

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [21]:
arr1=arr


In [22]:
arr1[3:]=500
print(arr1)

[  0   1   2 500 500 500 500 500 500 500]


In [23]:
arr

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [25]:
arr1 = arr.copy()
print(arr)

[  0   1   2 500 500 500 500 500 500 500]


In [26]:
arr1[3:]=1000
print(arr1)

[   0    1    2 1000 1000 1000 1000 1000 1000 1000]


In [27]:
### Some conditions very useful in exploratory data analysis
val = 2
arr < 2


array([ True,  True, False, False, False, False, False, False, False,
       False])

In [28]:
val = 2
arr * 2

array([   0,    2,    4, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [29]:
val = 2
arr/2

array([  0. ,   0.5,   1. , 250. , 250. , 250. , 250. , 250. , 250. ,
       250. ])

In [30]:
val = 2
arr%2

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0])