<a href="https://colab.research.google.com/github/Sanjayme049/Python/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Numpy is a general purpose array-processing package. It provides a high performance multidimensional arry object, and tools for working with these arrays. It is the fundamental package for scientific computing with python.


import numpy as np
my_list = [1,2,3,4,5]


In [2]:
arr = np.array(my_list)

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.shape

(5,)

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
arr

array([1, 2, 3, 4, 5])

In [7]:
##Multinested array
my_lst1 = [1,2,3,4,5]
my_lst2 = [2,3,4,5,6]
my_lst3 = [9,7,6,8,9]

arr = np.array([my_lst1,my_lst2,my_lst3])

In [8]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [9]:
arr.shape

(3, 5)

In [10]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])