<a href="https://colab.research.google.com/github/Sanjayme049/Python/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Numpy is a general purpose array-processing package. It provides a high performance multidimensional arry object, and tools for working with these arrays. It is the fundamental package for scientific computing with python.


import numpy as np
my_list = [1,2,3,4,5]


In [3]:
arr = np.array(my_list)

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.shape

(5,)

In [6]:
print(arr)

[1 2 3 4 5]


In [7]:
arr

array([1, 2, 3, 4, 5])

In [8]:
##Multinested array
my_lst1 = [1,2,3,4,5]
my_lst2 = [2,3,4,5,6]
my_lst3 = [9,7,6,8,9]

arr = np.array([my_lst1,my_lst2,my_lst3])

In [9]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [10]:
arr.shape

(3, 5)

In [13]:
# arr[0:2,0:2]
# arr[:,:3]
# arr[1:,3:]
arr[1:,:3]



array([[2, 3, 4],
       [9, 7, 6]])

In [14]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [15]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [ ]:
#arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9]])

In [ ]:
#Indexing in numpy

#Accessing the array element

arr=np.array([1,2,3,4,5,6,7,8,9])


In [ ]:
arr[3]

4

In [ ]:
# arr[5]

In [ ]:
 arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])