<a href="https://colab.research.google.com/github/Sanjayme049/Python/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
np.__version__

np.random.seed(42)
x = np.random.randint(0, 20, (2, 2,3, 2))

In [4]:
print(x)

[[[[ 6 19]
   [14 10]
   [ 7  6]]

  [[18 10]
   [10  3]
   [ 7  2]]]


 [[[ 1 11]
   [ 5  1]
   [ 0 11]]

  [[11 16]
   [ 9 15]
   [14 14]]]]


In [5]:
x[1][0]

array([[ 1, 11],
       [ 5,  1],
       [ 0, 11]])

In [12]:
x[1,0,1:]

array([[ 5,  1],
       [ 0, 11]])

In [11]:
np.random.seed(42)
y = np.random.randint(0, 20, (3, 2, 5, 4, 4))
print(y)

[[[[[ 6 19 14 10]
    [ 7  6 18 10]
    [10  3  7  2]
    [ 1 11  5  1]]

   [[ 0 11 11 16]
    [ 9 15 14 14]
    [18 11 19  2]
    [ 4 18  6  8]]

   [[ 6 17  3 13]
    [17  8  1 19]
    [14  6 11  7]
    [14  2 13 16]]

   [[ 3 17  7  3]
    [ 1  5  9  3]
    [17 11  1  9]
    [ 3 13 15 14]]

   [[ 7 13  7 15]
    [12 17 14 12]
    [ 8 14 12  0]
    [ 6  8  0 11]]]


  [[[ 7 10 18 16]
    [ 7  2  2  0]
    [ 4  9  6  8]
    [ 6  8  7 11]]

   [[ 1  0 15  4]
    [ 2 11  7  2]
    [ 0  2  4 14]
    [13  2  0  4]]

   [[13  6  8 14]
    [14  9 12 18]
    [ 6 16 19  3]
    [ 4  6 12 14]]

   [[10  3 12  6]
    [18  1  9 12]
    [ 5 11 11 19]
    [10  6  0  0]]

   [[19 12  8  2]
    [ 6  5  7  8]
    [ 4  0 18  9]
    [11 14  8 19]]]]



 [[[[16 16 19 11]
    [ 6  1  2 16]
    [ 4 16 16 16]
    [ 1  1  4  0]]

   [[ 0 18  1 11]
    [ 5  3 10 16]
    [ 5  4 19  1]
    [ 5 10 15 15]]

   [[ 0  8  5 15]
    [ 2 19  3 18]
    [ 2 18 19  6]
    [19  8  0  7]]

   [[ 6 17  7  0]
    [10 17  9 

In [ ]:



# y[2,0,1,1:]